import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import AnnouncementBar from "@/components/(a)/AnnouncementBar";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import {ClerkProvider} from "@clerk/nextjs";



const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Clothes",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
    <html lang="en">

      <body className={inter.className}>
   
<AnnouncementBar/>
<Header/>
   

          {children}
     
        <Footer/></body>
    </html>
    </ClerkProvider>
  );
}
